### ISSUE TITLE
v1.12.alpha.1 doesn't build a new project

### ISSUE THREAD

**Issue by admilazz** [kubernetes-incubator/apiserver-builder-alpha#317] opened 2019-03-08 19:22 UTC
I installed apiserver-builder and created a new project with these commands:

    $ apiserver-boot init repo --domain company.com
    $ apiserver-boot create group --group project
    $ apiserver-boot create version --group project --version v1alpha1
    $ apiserver-boot create resource --group project --version v1alpha1 --kind MyKind

The boilerplate.go.txt file just contained "// Copyright 2019 Company". Then I tried to build it with `apiserver-boot build generated`. The output was as follows:

    /home/adam/go/bin/apiregister-gen --input-dirs company.com/project/pkg/apis/... --input-dirs company.com/project/pkg/controller/...
    /home/adam/go/bin/conversion-gen --input-dirs company.com/project/pkg/apis/project/v1alpha1 --input-dirs company.com/project/pkg/apis/project -o /home/adam/go/src --go-header-file boilerplate.go.txt -O zz_generated.conversion --extra-peer-dirs k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime
    /home/adam/go/bin/deepcopy-gen --input-dirs company.com/project/pkg/apis/project/v1alpha1 --input-dirs company.com/project/pkg/apis/project -o /home/adam/go/src --go-header-file boilerplate.go.txt -O zz_generated.deepcopy
    /home/adam/go/bin/openapi-gen --input-dirs company.com/project/pkg/apis/project/v1alpha1 -o /home/adam/go/src --go-header-file boilerplate.go.txt -i k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/api/resource,k8s.io/apimachinery/pkg/version,k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/util/intstr,k8s.io/api/admission/v1beta1,k8s.io/api/admissionregistration/v1alpha1,k8s.io/api/admissionregistration/v1beta1,k8s.io/api/apps/v1,k8s.io/api/apps/v1beta1,k8s.io/api/apps/v1beta2,k8s.io/api/authentication/v1,k8s.io/api/authentication/v1beta1,k8s.io/api/authorization/v1,k8s.io/api/authorization/v1beta1,k8s.io/api/autoscaling/v1,k8s.io/api/autoscaling/v2beta1,k8s.io/api/autoscaling/v2beta2,k8s.io/api/batch/v1,k8s.io/api/batch/v1beta1,k8s.io/api/batch/v2alpha1,k8s.io/api/certificates/v1beta1,k8s.io/api/coordination/v1beta1,k8s.io/api/core/v1,k8s.io/api/events/v1beta1,k8s.io/api/extensions/v1beta1,k8s.io/api/networking/v1,k8s.io/api/policy/v1beta1,k8s.io/api/rbac/v1,k8s.io/api/rbac/v1alpha1,k8s.io/api/rbac/v1beta1,k8s.io/api/scheduling/v1alpha1,k8s.io/api/scheduling/v1beta1,k8s.io/api/settings/v1alpha1,k8s.io/api/storage/v1,k8s.io/api/storage/v1alpha1,k8s.io/api/storage/v1beta1,k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1,k8s.io/client-go/pkg/apis/clientauthentication/v1beta1,k8s.io/api/core/v1 --report-filename violations.report --output-package company.com/project/pkg/openapi
    2019/03/08 19:11:13 failed to run openapi-gen E0308 19:11:13.368394   16501 openapi.go:365] Error when generating: Duration, Duration invalid type
    2019/03/08 19:11:13 OpenAPI code generation error: Failed executing generator: some packages had errors:
    cannot generate spec for type invalid type
     exit status 1

Searching for the Duration type that openapi-gen complains about shows that they all come from the vendored libraries packaged with apiserver-builder. At least, none of them are coming from "my" code (which is just the autogenerated result of the four commands above).

openapi-gen is the version packaged with apiserver-builder.

Go is version 1.11.5.

**Comment by yue9944882** [comment] 2019-03-09 06:45
> Searching for the Duration type that openapi-gen complains about shows that they all come from the vendored libraries packaged with apiserver-builder.

how to reproduce that? could u paste me a minimum definition of ur `company.com/project/pkg/apis/project/v1alpha1` API ?

**Comment by admilazz** [comment] 2019-03-09 18:06
The API has not been modified from whatever was generated by apiserver-boot. That is to say, I just ran those four apiserver-boot commands above and tried to build it. So, to reproduce it, just run these commands:

    $ touch boilerplate.go.txt
    $ apiserver-boot init repo --domain company.com
    $ apiserver-boot create group --group project
    $ apiserver-boot create version --group project --version v1alpha1
    $ apiserver-boot create resource --group project --version v1alpha1 --kind MyKind
    $ apiserver-boot build generated

And it fails with the error I gave.

**Comment by yue9944882** [comment] 2019-03-11 03:38
> And it fails with the error I gave.

am i missing sth? i tried running the commands step by step but didn't reproduce the error. could u run `which openapi-gen` and see if it's under `$GOPATH/bin`?

**Comment by yue9944882** [comment] 2019-03-11 07:28
oh, reproduced.. fixing soon

**Comment by yue9944882** [comment] 2019-03-11 09:30
@admilazz finally, i find out it was the `GOROOT` env var missing that caused this very error. export this env var and the openapi-gen will run fine. 

closing this issue, feel free to reopen if it still doesn't get solved
/close

**Comment by yue9944882** [comment] 2019-03-11 10:03
@admilazz 

a walkround for this issue will be exporting `GOROOT` env var explicitly in your shell context

**Comment by admilazz** [comment] 2019-03-11 17:16
Thanks, I'll try the workaround.

**Comment by admilazz** [comment] 2019-03-11 19:23
I still get the error, unfortunately.

export GOROOT=/usr/local/go
export GOPATH=/home/adam/go
export PATH=$PATH:$GOPATH/bin
...

**Comment by yue9944882** [comment] 2019-03-12 04:30
the crux is that GOROOT didn't get correctly loaded in the generator's parser. w/o GOROOT any types defined in golang SDK will not be parsed when generating openapi doc. 

[https://github.com/kubernetes/gengo/blob/b90029ef6cd877cb3f422d75b3a07707e3aac6b7/parser/parse.go#L86](https://github.com/kubernetes/gengo/blob/b90029ef6cd877cb3f422d75b3a07707e3aac6b7/parser/parse.go#L86)

> c := build.Default

**Closed** 2019-03-12 10:48 UTC

**Comment by yue9944882** [comment] 2019-03-12 12:25
fixed in release `v1.12.alpha.2`, feel free to reopen this issue

**Comment by admilazz** [comment] 2019-03-13 16:43
Just have to say that I get the exact same error with v1.12.alpha.2.

**Comment by admilazz** [comment] 2019-03-13 16:49
I did eventually get it to build by playing around with the GOROOT, but it's interesting that other tools don't seem to need that.

**Comment by jhedev** [comment] 2019-06-01 13:43
I'm facing the same issue with v1.12.alpha.3 on a newly initialized project... any changes to GOROOT do not help. Any idea how I can get it working?

**Comment by yue9944882** [comment] 2019-06-04 07:27
@jhedev what's your output running `go env` and `echo $GOROOT` in the command-line context?

**Comment by jhedev** [comment] 2019-06-04 17:09
```shell
$ go env
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/joel/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/joel/code/go/"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/88/q0fjn79j3h16rp4c6h8jy8000000gn/T/go-build971423920=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

```
$ echo $GOROOT

```

If I set `GOROOT=/usr/local/go` it seems to fix the open-api generation part but break the other builds. So I have to do the following: `GOROOT=/usr/local/go apiserver-boot build generated` followed by `apiserver-boot build executables --generate=false` to build executables because setting `GOROOT` to `/usr/local/go` will break `go build`
